package com.sfc.project.product_service.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

@Entity // Marks this class as a JPA entity, mapped to a database table
@Table(name = "products") // Specifies the name of the database table
@Data // Lombok: Generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok: Generates a no-argument constructor
@AllArgsConstructor // Lombok: Generates a constructor with all fields as arguments
@Getter // Lombok: Generates getter methods
@Setter // Lombok: Generates setter methods
public class Product {
        @Id // Marks this field as the primary key of the entity
        @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database
        private Long id;

        @Column(nullable = false, unique = true) // Ensures the 'name' column is not null and unique
        private String name;

        private String description;

        @Column(nullable = false) // Ensures 'price' column is not null
        private BigDecimal price;

        @Column(nullable = false) // Ensures 'quantity' column is not null
        private Integer quantity; // Represents stock quantity

        private String category;
}
